apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasktracker-web
  namespace: tasktracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasktracker
  template:
    metadata:
      labels:
        app: tasktracker
    spec:
      containers:
      - name: web-app
        image: rigistry.azurecr.io/tasktracker:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://ammar:B$f123456789@postgresql-server737.postgres.database.azure.com:5432/postgres?sslmode=require"
---
apiVersion: v1
kind: Service
metadata:
  name: tasktracker-service
  namespace: tasktracker
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: tasktracker
